export const INSULTS = [
    "You're not the dumbest person in the world, but you better hope they don't die.",
    "If I wanted to kill myself, I'd climb your ego and jump to your IQ.",
    "You're the reason the gene pool needs a lifeguard.",
    "You must have been born on a highway, because that's where most accidents happen.",
    "I'd agree with you but then we’d both be wrong.",
    "You're so ugly when your mom dropped you off at school, she got a fine for littering.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "You're as bright as a black hole, and twice as dense.",
    "I’d explain it to you, but I left my English-to-Dumbass Dictionary at home.",
    "You're the reason God created the middle finger.",
    "Your birth certificate is an apology letter from the condom factory.",
    "You're so ugly, when you threw a boomerang, it refused to come back.",
    "It's impossible to underestimate you.",
    "You're as useful as a knitted condom.",
    "You're the human equivalent of a participation award.",
    "I'd like to see things from your point of view, but I can't seem to get my head that far up my ass.",
    "I'd slap you, but that would be animal abuse.",
    "You're so fake, Barbie is jealous.",
    "If ignorance is bliss, you must be the happiest person on earth.",
    "I'm not insulting you; I'm describing you.",
    "You're as irrelevant as the 'ueue' in 'queue'.",
    "Your family tree must be a cactus, because everybody on it is a prick.",
    "You're the reason the phrase 'it could be worse' was invented.",
    "You have the right to remain silent because whatever you say will probably be stupid anyway.",
    "You're not stupid; you're just possessed by a retarded ghost.",
    "Why don't you slip into something more comfortable, like a coma?",
    "I'd like to help you out. Which way did you come in?",
    "You're so ugly, when you popped out the doctor said 'What a treasure!' and your mom said 'Yeah, let's bury it.'",
    "You have two parts of brain, 'left' and 'right'. In your left side, there’s nothing right. In your right side, there’s nothing left.",
    "You're so ugly, you scared the crap out of the toilet.",
    "It’s not that I’m smarter than you, it’s just that you’re dumber than everyone else.",
    "You're so fat, when you went to the beach all the whales started singing 'We Are Family'.",
    "You are proof that evolution CAN go in reverse.",
    "You're not yourself today. I noticed the improvement immediately.",
    "You're so ugly, when you got robbed, the robbers made you wear their masks.",
    "You're as pointless as a screen door on a submarine.",
    "You're like a cloud. When you disappear, it’s a beautiful day.",
    "I’d give you a nasty look but you’ve already got one.",
    "You're so fat, you leave footprints in concrete.",
    "I’d insult you, but you’re not bright enough to notice.",
    "You're so ugly, your portraits hang themselves.",
    "Your mind is on vacation but your mouth is working overtime.",
    "You're so old, your birth certificate says 'Expired' on it.",
    "You're so ugly, you make onions cry.",
    "I'd say you're as boring as watching paint dry, but at least paint eventually gets interesting.",
    "You're so fat, when you step on the scale it says 'To be continued...'",
    "You're not lazy, you're just on energy saving mode.",
    "If you were twice as smart, you'd still be stupid.",
    "You're so ugly, when you looked in the mirror, your reflection walked away.",
    "You're so fat, you don't need the internet; you're already worldwide.",
    "I don’t have the time or the crayons to explain this to you.",
    "You're so ugly, when we play hide and seek, I don’t look for you.",
    "You're not a complete idiot; some parts are obviously missing.",
    "You're so fat, your school pictures were taken by satellite.",
    "I'd challenge you to a battle of wits, but I see you're unarmed.",
    "You're the proof that one can live without a brain!",
    "You're so confusing, even Siri ignores your questions.",
    "You have a face only a mother could love, and she's pushing it.",
    "You're so irrelevant, you're like the terms and conditions.",
    "You're as welcome as a paper cut.",
    "You're the human version of a headache.",
    "You're like Monday mornings, nobody likes you.",
    "You're so old, you fart dust.",
    "You're so boring, you could make a happy meal cry.",
    "You're like a software update, every time I see you, I immediately want to postpone.",
    "You're like a slinky, not really good for anything, but you bring a smile when pushed down the stairs.",
    "If you were a vegetable, you'd be a 'cabbitch'.",
    "You're the reason we can't have nice things.",
    "You're so ugly, when you go camping, the bears hide their food.",
    "If you were on fire and I had water, I'd drink it.",
    "You're like a glow stick, I want to snap you and shake the sense into you.",
    "You're as useful as the 'ueue' in 'queue'.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "You're like a cloud. When you go away, the day gets brighter.",
    "You're not the sharpest tool in the shed, you're the gardening manual.",
    "You're so annoying, you could make an onion cry.",
    "You're so ugly, your pet names you 'human'.",
    "You're as bright as a black hole, and significantly less appealing.",
    "If you were a spice, you'd be flour.",
    "You're so boring, even a snail says you need to liven things up.",
    "You're the reason we have instructions on shampoo bottles.",
    "If I threw a stick, you'd leave, right?",
    "You're so old, you walked into an antique store and they kept you.",
    "You're like the end pieces of bread, everyone touches you, but nobody wants you.",
    "You're the human equivalent of a participation certificate.",
    "If brains were gasoline, you wouldn't have enough to power an ant's motorcycle around the inside of a Cheerio.",
    "You're like a software terms of service – everyone just skips over you.",
    "You're so ugly, when you look in the mirror, your reflection looks away.",
    "If laziness was a profession, you'd be a billionaire.",
    "You're like a puzzle with missing pieces – impossible to figure out and all over the place.",
    "Your cooking is so bad, the flies pitched in to fix the screen door.",
    "You're like a broken pencil: pointless.",
    "You're the reason the middle finger was invented.",
    "You're like a library book – too many issues.",
    "You're so ugly, you didn't go through puberty; puberty went through you.",
    "You're as useless as the 'G' in lasagna.",
    "You're like a bag of pampers – self-absorbed and full of... well, you know.",
    "If dumb were dirt, you'd cover an acre.",
    "You're so old, your birth certificate is in Roman numerals.",
    "You're so ugly, when you cry, the tears roll down the back of your head to avoid your face.",
    "You're the reason they invented double doors.",
    "You're so boring, you can't even entertain a doubt.",
    "You're like a car with no engine – you've got a shiny exterior, but you're going nowhere.",
    "If you were a flavor, you'd be plain yogurt.",
    "You're the human version of a typo.",
    "You're so ugly, when you were born, the doctor slapped your parents.",
    "You're like a bar of soap – the more you're used, the thinner and more slippery you become.",
    "If you were a box of crayons, you'd be the white one that never gets used.",
    "You're the reason people double check their locks at night.",
    "You're as useful as a screen door on a submarine.",
    "You're like expired milk – chunky and sour.",
    "You're so ugly, when you play Mortal Kombat, Scorpion says 'Stay over there!'",
    "If you were any more inbred, you'd be a sandwich.",
    "You're like a traffic jam – everybody dislikes you, and you never seem to end.",
    "You're so stupid, you got hit by a parked car.",
    "You're so useless, you could turn a gold medal into a participation trophy.",
    "You're like a math problem: people skip you.",
    "If you were a color, you'd be transparent because you're barely noticed.",
    "You're like a typo in an important email, immediately noticeable and permanently embarrassing.",
    "You're the reason there are instructions on Pop-Tarts.",
    "You're so irrelevant, you could be the 'Terms and Conditions' and no one would notice.",
    "If being boring was a crime, you'd be serving a life sentence.",
    "You're like a GPS with no signal — you pretend to know the way, but everyone knows you're lost.",
    "You're the human equivalent of a wet sock.",
    "You're like a mystery book with the last page missing.",
    "If laziness was a professional sport, you'd be an Olympian.",
    "You're so dense, light bends around you.",
    "You're like a password, easily forgotten.",
    "You're as meaningful as a white crayon.",
    "You're like a mosquito, annoying and unfortunately everywhere.",
    "If you were an app, you'd be Clippy — annoying and unwanted.",
    "You're like a cloudy day, dull and depressing.",
    "You're the human version of a blunder.",
    "You're like a silent alarm, completely ineffective.",
    "You're as useful as a chocolate teapot.",
    "You're like a phone on airplane mode — no one can reach you, and you're not useful.",
    "If you were a book, you'd be in the free bin.",
    "You're the reason alien civilizations refuse to communicate with us.",
    "You're like a broken escalator, temporarily stairs and just as disappointing.",
    "You're as unnoticed as the 'P' in psychology.",
    "You're like a reality TV show — lots of drama but no substance.",
    "You're so unnecessary, you're like the 'ay' in 'okay'.",
    "You're like a candle that won't light — pointless and frustrating.",
    "If you were a plant, you'd be a cactus, because you're prickly and everyone avoids you.",
    "You're the human equivalent of a flat tire.",
    "You're like an artichoke, tough and mostly heartless.",
    "You're as compelling as a loaf of bread.",
    "You're like the end of a loaf of bread, everyone touches you but no one wants you.",
    "You're the visual equivalent of elevator music.",
    "If you were a movie, you'd be straight to DVD.",
    "You're like a lost sock, no one knows where you are or cares.",
    "You're the human version of a participation ribbon.",
    "You're like decaf coffee, you promise a lot but deliver little.",
    "You're as essential as the 'ueue' in 'queue'.",
    "You're like a software update in the middle of a phone call, unnecessary and ill-timed.",
    "You're the reason there's a setting for 'low brightness' on every device.",
    "You're like a Sunday evening, nobody looks forward to dealing with you.",
    "You're the kind of person who reads a pizza recipe on the box.",
    "You're like an old browser, too many issues and constantly crashing.",
    "You're as impactful as an echo in an empty room.",
    "You're like a puzzle with all edge pieces, difficult and unsatisfying.",
    "If you were a vegetable, you'd be a 'bitter melon'.",
    "You're the 'read receipt' of human interactions, noticed but unappreciated.",
    "You're as memorable as a dream after waking up.",
    "You're the reason there are warning labels on everything."
]



