on:
  pull_request:
    branches:
      - master
    tags:
      - opened
      - synchronize
jobs:
  build-node:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build
        run: npm run build

      - name: Deploy
        run: mv -f ./* /opt/crash_bot/